### ISSUE TITLE
System.InvalidOperationException: A task may only be disposed if it is in a completion stat

### ISSUE THREAD

**Issue by carlosalbertosousa** [wcoder/PeriodicBackgroundService#1]
error in the method OnDestroy in _task._task.Dispose();

Unhandled Exception:

System.InvalidOperationException: A task may only be disposed if it is in a completion state (RanToCompletion, Faulted or Canceled).

> public override void OnDestroy()
>       {
>           _isRunning = false;
> 
> ```
>       if (_task != null)
>       {
>           _task.Dispose();
>       }
>   }
> ```

**Comment by hassanbht** [comment]
add 

```cs
if (_task != null && _task.Status == TaskStatus.RanToCompletion)
{
    _task.Dispose();
}
```
