### ISSUE TITLE
Is not firing properlly

### ISSUE THREAD

**Issue by mfandre** [wcoder/PeriodicBackgroundService#3]
This code just fire at the first start. 

For example, if I close the app the background service stops and never will be called again.

**Comment by yauhenipakala** [comment]
Hi, this sample project not up to date some time, could you provide more details about your case, which platform for example? Also, you can look at the latest [README.md](https://github.com/wcoder/PeriodicBackgroundService/blob/master/README.md) file for materials about better approaches to make background tasks.
